/**
 * Voice generators.
 *
 * Three of the four voices are synthesised with the Web Audio API:
 *   - kick: a sine oscillator whose pitch falls from 150 to ~50 Hz
 *   - hat:  a short burst of highpass-filtered white noise
 *   - clap: a stack of four short noise bursts, the last one longer
 *
 * The snare is a small WAV sample. The sample is itself synthetic
 * (noise + tonal "ping"), generated by a Python script at build time
 * and shipped in /public/snare.wav. You can drop in your own snare
 * by replacing that file.
 */

export interface Voice {
  trigger(time: number): void;
}

/* ---------- helpers ---------- */

function createNoiseBuffer(ctx: AudioContext, durationMs: number): AudioBuffer {
  const length = Math.floor((ctx.sampleRate * durationMs) / 1000);
  const buffer = ctx.createBuffer(1, length, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < length; i++) {
    data[i] = Math.random() * 2 - 1;
  }
  return buffer;
}

function envGain(
  ctx: AudioContext,
  time: number,
  attack: number,
  decay: number,
  peak = 1,
): GainNode {
  const g = ctx.createGain();
  g.gain.setValueAtTime(0, time);
  g.gain.linearRampToValueAtTime(peak, time + attack);
  g.gain.exponentialRampToValueAtTime(0.0001, time + attack + decay);
  return g;
}

/* ---------- kick ---------- */

export function createKick(ctx: AudioContext, master: AudioNode): Voice {
  return {
    trigger(time: number) {
      const osc = ctx.createOscillator();
      osc.type = "sine";
      osc.frequency.setValueAtTime(150, time);
      osc.frequency.exponentialRampToValueAtTime(45, time + 0.18);

      const env = envGain(ctx, time, 0.001, 0.4, 1.1);
      // Body
      osc.connect(env).connect(master);
      osc.start(time);
      osc.stop(time + 0.45);

      // Click for punch
      const noiseBuf = createNoiseBuffer(ctx, 8);
      const click = ctx.createBufferSource();
      click.buffer = noiseBuf;
      const clickHp = ctx.createBiquadFilter();
      clickHp.type = "highpass";
      clickHp.frequency.value = 2000;
      const clickEnv = envGain(ctx, time, 0.001, 0.012, 0.35);
      click.connect(clickHp).connect(clickEnv).connect(master);
      click.start(time);
      click.stop(time + 0.05);
    },
  };
}

/* ---------- hi-hat ---------- */

export function createHat(ctx: AudioContext, master: AudioNode): Voice {
  return {
    trigger(time: number) {
      const noiseBuf = createNoiseBuffer(ctx, 80);
      const src = ctx.createBufferSource();
      src.buffer = noiseBuf;

      const hp = ctx.createBiquadFilter();
      hp.type = "highpass";
      hp.frequency.value = 7000;

      const bp = ctx.createBiquadFilter();
      bp.type = "bandpass";
      bp.frequency.value = 10000;
      bp.Q.value = 0.8;

      const env = envGain(ctx, time, 0.001, 0.05, 0.55);

      src.connect(hp).connect(bp).connect(env).connect(master);
      src.start(time);
      src.stop(time + 0.1);
    },
  };
}

/* ---------- clap ---------- */

export function createClap(ctx: AudioContext, master: AudioNode): Voice {
  return {
    trigger(time: number) {
      // Three quick noise bursts + one longer tail — classic clap stack
      const offsets = [0, 0.01, 0.02];
      for (const offset of offsets) {
        const noiseBuf = createNoiseBuffer(ctx, 10);
        const src = ctx.createBufferSource();
        src.buffer = noiseBuf;
        const bp = ctx.createBiquadFilter();
        bp.type = "bandpass";
        bp.frequency.value = 1200;
        bp.Q.value = 2;
        const env = envGain(ctx, time + offset, 0.001, 0.012, 0.6);
        src.connect(bp).connect(env).connect(master);
        src.start(time + offset);
        src.stop(time + offset + 0.05);
      }
      // Longer tail
      const tailBuf = createNoiseBuffer(ctx, 90);
      const tail = ctx.createBufferSource();
      tail.buffer = tailBuf;
      const tailBp = ctx.createBiquadFilter();
      tailBp.type = "bandpass";
      tailBp.frequency.value = 1100;
      tailBp.Q.value = 1.6;
      const tailEnv = envGain(ctx, time + 0.025, 0.001, 0.08, 0.35);
      tail.connect(tailBp).connect(tailEnv).connect(master);
      tail.start(time + 0.025);
      tail.stop(time + 0.15);
    },
  };
}

/* ---------- snare (sampler) ---------- */

export interface SampleVoice extends Voice {
  load(url: string): Promise<void>;
}

export function createSnareSampler(
  ctx: AudioContext,
  master: AudioNode,
): SampleVoice {
  let buffer: AudioBuffer | null = null;

  return {
    async load(url: string) {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`Failed to load ${url}: ${res.status}`);
      const arr = await res.arrayBuffer();
      buffer = await ctx.decodeAudioData(arr);
    },
    trigger(time: number) {
      if (!buffer) return;
      const src = ctx.createBufferSource();
      src.buffer = buffer;
      const g = ctx.createGain();
      g.gain.value = 0.85;
      src.connect(g).connect(master);
      src.start(time);
    },
  };
}
